2024-11-02 16:32:42.195324+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:31)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 16:33:23.760931+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:31)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 16:53:46.157529+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY NOT  NULL
) [42001-232]
2024-11-02 16:55:45.573507+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:33)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 16:55:45.639466+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:19)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 16:57:01.740864+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:33)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 16:57:01.794831+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:19)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 16:57:14.811470+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:00:29.162285+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:00:40.338145+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:00:50.013809+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:00:50.079912+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "CUSTOMERS" не найдена
Table "CUSTOMERS" not found; SQL statement:
INSERT into CUSTOMERS values (Иванов, true, Иванович, 1920564736, [models.BankAccount@3b07a0d6] ); [42102-232]
2024-11-02 17:02:45.725300+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:02:45.803251+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values (Иванов, true, Иванович, 1920564736, [models.BankAccount@[*]79efed2d] );"; ожидалось "Approximate numeric"
Syntax error in SQL statement "INSERT into HOLDERSDB values (Иванов, true, Иванович, 1920564736, [models.BankAccount@[*]79efed2d] );"; expected "Approximate numeric"; SQL statement:
INSERT into HOLDERSDB values (Иванов, true, Иванович, 1920564736, [models.BankAccount@79efed2d] ); [42001-232]
2024-11-02 17:03:09.567277+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:03:09.660260+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values (Иванов, Иван, Иванович, 1920564736, [*][models.BankAccount@2805c96b] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT into HOLDERSDB values (Иванов, Иван, Иванович, 1920564736, [*][models.BankAccount@2805c96b] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT into HOLDERSDB values (Иванов, Иван, Иванович, 1920564736, [models.BankAccount@2805c96b] ); [42001-232]
2024-11-02 17:10:07.022233+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 17:10:07.079248+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@1e730495] ); [42001-232]
2024-11-02 18:02:21.187051+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:02:21.256123+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO HOLDERSDB (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:04:21.109684+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:04:21.188635+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO holdersdb (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:05:17.827136+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:05:17.883153+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO holdersdb (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:06:10.721406+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:06:10.786400+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO holdersdb (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:08:35.908516+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:08:35.985510+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO holdersdb (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:08:40.540267+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:11:04.780343+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO holdersdb (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:13:51.198486+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:35)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 18:14:04.284079+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:19)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 18:14:13.665177+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:35)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:15)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 18:14:18.515889+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:19)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 18:14:37.468941+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:14:37.566998+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO HOLDERSDB (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:14:45.602094+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:14:45.654103+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO HOLDERSDB (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:14:52.458485+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:16:52.969938+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO HOLDERSDB (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:31:01.085375+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:31:01.159483+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Схема "HOLDER" не найдена
Schema "HOLDER" not found; SQL statement:
INSERT INTO HOLDERSDB (name, surname, patronymic, passportNumberAndSeries, bankAccounts) VALUES (holder.getName(), holder.getSurname(), holder.getPatronymic(), holder.getPassportNumberAndSeries(), holder.getBankAccounts()) [90079-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Database.getSchema(Database.java:1577)
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4794)
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5144)
	at org.h2.command.Parser.readTerm(Parser.java:4828)
	at org.h2.command.Parser.readFactor(Parser.java:3323)
	at org.h2.command.Parser.readSum(Parser.java:3310)
	at org.h2.command.Parser.readConcat(Parser.java:3275)
	at org.h2.command.Parser.readCondition(Parser.java:3065)
	at org.h2.command.Parser.readExpression(Parser.java:2985)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:2971)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1685)
	at org.h2.command.Parser.parseInsert(Parser.java:1550)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:94)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:24)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:32:48.833239+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:32:48.907194+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@2805c96b] ); [42001-232]
2024-11-02 18:36:20.534195+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:36:20.595157+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@1e730495] ); [42001-232]
2024-11-02 18:36:43.315017+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:36:43.388100+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT into HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@2805c96b] ); [42001-232]
2024-11-02 18:37:20.824706+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:37:20.901659+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB values ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@2805c96b] ); [42001-232]
2024-11-02 18:40:19.435058+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:40:19.492065+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@1e730495] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@1e730495] ); [42001-232]
2024-11-02 18:42:33.137896+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES ('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495] )"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES ('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495] )"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES ('Артём', 'Кузнецов', 'Александрович', 2020445566, [models.BankAccount@1e730495] ) [42001-232]
2024-11-02 18:46:06.931845+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495])"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495])"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [models.BankAccount@1e730495]) [42001-232]
2024-11-02 18:46:08.118276+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495])"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [*][models.BankAccount@1e730495])"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566, [models.BankAccount@1e730495]) [42001-232]
2024-11-02 18:46:20.222049+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO HOLDERSDB VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566) [21002-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:294)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-02 18:49:20.644705+03:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccountsVARCHAR[*](30) NOT NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccountsVARCHAR[*](30) NOT NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccountsVARCHAR(30) NOT NULL
) [42001-232]
2024-11-02 18:49:46.797297+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:49:46.880245+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@2805c96b] );"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@2805c96b] ); [42001-232]
2024-11-02 18:52:18.798347+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "TEST" не найдена
Table "TEST" not found; SQL statement:
INSERT INTO TEST VALUES('Артём', 'Кузнецов', 'Александрович', 2020445566 , '[models.BankAccount@2805c96b]') [42102-232]
2024-11-02 18:55:22.195683+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:36)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:17)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 18:55:22.229663+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:21)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 18:55:37.888750+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:55:37.952747+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES('/s', '/s', '/s', [*]/s , '/s');"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES('/s', '/s', '/s', [*]/s , '/s');"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES('/s', '/s', '/s', /s , '/s'); [42001-232]
2024-11-02 18:56:09.510763+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:56:09.576777+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB VALUES(' ', ' ', ' ',   [*], ' ');"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB VALUES(' ', ' ', ' ',   [*], ' ');"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB VALUES(' ', ' ', ' ',   , ' '); [42001-232]
2024-11-02 18:57:00.894742+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 18:57:00.978725+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Метод разрешен только для запросов. Используйте execute или executeUpdate вместо executeQuery
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
INSERT INTO HOLDERSDB VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , '[models.BankAccount@75f32542]') [90002-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.Prepared.query(Prepared.java:250)
	at org.h2.command.CommandContainer.query(CommandContainer.java:222)
	at org.h2.command.Command.executeQuery(Command.java:196)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:101)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:25)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-02 18:57:53.729122+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:03:37.777555+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "SHOW [*]HOLDERSDB"
Syntax error in SQL statement "SHOW [*]HOLDERSDB"; SQL statement:
SHOW HOLDERSDB [42000-232]
2024-11-02 19:10:45.669732+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:37)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:17)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 19:10:45.707709+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:21)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 19:10:59.203145+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:10:59.992055+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:11:00.583182+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:11:01.544130+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:13:38.823655+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:37)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:17)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-02 19:13:46.855745+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:21)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-02 19:14:39.741673+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:39.891629+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:39.987604+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:40.086706+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:47.257404+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:47.404409+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:47.520605+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:14:47.623649+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:15:37.832447+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:15:47.829848+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:09.142063+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:10.256637+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:17.750851+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:18.100056+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:18.369388+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:16:18.659757+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:17:53.786312+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:18:22.906410+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:18:42.828943+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:18:42.984959+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:18:43.284350+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:18:43.391345+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:01.891229+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:02.025422+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:02.128425+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:02.228488+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:16.788893+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:16.919888+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:17.023003+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-02 19:19:17.126089+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:14:05.609116+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:37)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:17)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-05 15:14:05.662083+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:21)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-05 15:14:36.686059+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:14:36.770063+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Ошибка преобразования данных при конвертации "'[models.BankAccount@2fd6b6c7]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"
Data conversion error converting "'[models.BankAccount@2fd6b6c7]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"; SQL statement:
INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , '[models.BankAccount@2fd6b6c7]') [22018-232]
2024-11-05 15:15:12.977350+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:15:13.071372+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Ошибка преобразования данных при конвертации "'[models.BankAccount@223f3642]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"
Data conversion error converting "'[models.BankAccount@223f3642]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"; SQL statement:
INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , '[models.BankAccount@223f3642]') [22018-232]
2024-11-05 15:15:39.221150+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:15:39.329152+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , [*][models.BankAccount@223f3642]);"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , [*][models.BankAccount@223f3642]);"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , [models.BankAccount@223f3642]); [42001-232]
2024-11-05 15:16:12.453536+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:16:12.557511+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Ошибка преобразования данных при конвертации "'[models.BankAccount@223f3642]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"
Data conversion error converting "'[models.BankAccount@223f3642]' (HOLDERSDB1: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"; SQL statement:
INSERT INTO HOLDERSDB1 VALUES('Иванов', 'Иван', 'Иванович', 1920564736 , '[models.BankAccount@223f3642]') [22018-232]
2024-11-05 15:17:43.819583+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "DROP [*]HOLDERSDB1 IF EXISTS TEST"; ожидалось "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, MATERIALIZED, VIEW, ROLE, ALIAS, SCHEMA, ALL OBJECTS, DOMAIN, TYPE, AGGREGATE, SYNONYM"
Syntax error in SQL statement "DROP [*]HOLDERSDB1 IF EXISTS TEST"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, MATERIALIZED, VIEW, ROLE, ALIAS, SCHEMA, ALL OBJECTS, DOMAIN, TYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP HOLDERSDB1 IF EXISTS TEST [42001-232]
2024-11-05 15:18:37.950861+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY NOT  NULL
) [42001-232]
2024-11-05 15:19:04.671882+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY BankAcccount NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY BankAcccount NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY BankAcccount NOT  NULL
) [42001-232]
2024-11-05 15:27:42.427419+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB1 ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY NOT  NULL
) [42001-232]
2024-11-05 15:28:56.395646+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB1 ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY NOT  NULL
) [42001-232]
2024-11-05 15:32:58.107609+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY JAVA_OBJECT NOT  NULL\000d\000a)"; ожидалось "data type"
Syntax error in SQL statement "CREATE TABLE HOLDERSDB1 ( \000d\000a name VARCHAR(20) NOT NULL,\000d\000a surname VARCHAR(20) NOT NULL, \000d\000a patronymic VARCHAR(20),  \000d\000a passportNumberAndSeries INT NOT NULL, \000d\000a bankAccounts [*]ARRAY JAVA_OBJECT NOT  NULL\000d\000a)"; expected "data type"; SQL statement:
CREATE TABLE HOLDERSDB1 ( 
 name VARCHAR(20) NOT NULL,
 surname VARCHAR(20) NOT NULL, 
 patronymic VARCHAR(20),  
 passportNumberAndSeries INT NOT NULL, 
 bankAccounts ARRAY JAVA_OBJECT NOT  NULL
) [42001-232]
2024-11-05 15:47:49.036285+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 15:47:49.133346+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "PASSPORTNUMBERANDSERIESY" не найден
Column "PASSPORTNUMBERANDSERIESY" not found; SQL statement:
INSERT INTO HOLDERSDB1  (name, surname, patronymic, passportNumberAndSeriesy, bankAccounts) VALUES  (?, ?, ?, ?, ?); [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:786)
	at org.h2.command.Parser.parseColumn(Parser.java:1171)
	at org.h2.command.Parser.parseColumnList(Parser.java:1156)
	at org.h2.command.Parser.parseInsert(Parser.java:1530)
	at org.h2.command.Parser.parsePrepared(Parser.java:698)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:315)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:24)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
2024-11-05 15:49:03.428691+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:17:17.202962+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:19:17.394894+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:35)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:17)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-05 16:19:17.432871+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:21)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-05 16:19:30.313507+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:22:55.280671+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, '[models.BankAccount@52e677af]'[*]"; ожидалось "[, ., ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, '[models.BankAccount@52e677af]'[*]"; expected "[, ., ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, '[models.BankAccount@52e677af]' [42001-232]
2024-11-05 16:23:31.563941+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@52e677af]"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@52e677af]"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@52e677af] [42001-232]
2024-11-05 16:24:09.964642+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@55a1c291]);"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [*][models.BankAccount@55a1c291]);"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, [models.BankAccount@55a1c291]); [42001-232]
2024-11-05 16:24:21.063847+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Ошибка преобразования данных при конвертации "'[models.BankAccount@52e677af]' (HOLDERSDB2: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"
Data conversion error converting "'[models.BankAccount@52e677af]' (HOLDERSDB2: ""BANKACCOUNTS"" JAVA_OBJECT NOT NULL)"; SQL statement:
INSERT INTO HOLDERSDB2 VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, '[models.BankAccount@52e677af]') [22018-232]
2024-11-05 16:41:27.523511+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:37)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:18)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-05 16:41:27.560488+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-05 16:43:03.520018+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Значение слишком длинное для поля "BANKACCOUNTS CHARACTER VARYING(30)": "'rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3I... (556)"
Value too long for column "BANKACCOUNTS CHARACTER VARYING(30)": "'rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3I... (556)"; SQL statement:
INSERT INTO HOLDERSDB VALUES ('Иванов', 'Иван', 'Иванович', 1920564736, 'rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3IAEm1vZGVscy5CYW5rQWNjb3VudCEkdWMM/nJQAgADTAANYWNjb3VudE51bWJlcnQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEGJhbGFuY2VPbkFjY291bnR0ABBMamF2YS9sYW5nL0xvbmc7TAATaGlzdG9yeU9mT3BlcmF0aW9uc3QAHExtb2RlbHMvSGlzdG9yeU9mT3BlcmF0aW9uczt4cHQAFDQ1OTQwNjU4OTg1Nzg1OTg2NzM1c3IADmphdmEubGFuZy5Mb25nO4vkkMyPI98CAAFKAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAAAAAAAc3IAGm1vZGVscy5IaXN0b3J5T2ZPcGVyYXRpb25zauWczKocahECAAFMAAdoaXN0b3J5dAAVTGphdmEvdXRpbC9BcnJheUxpc3Q7eHBzcQB+AAAAAAAAdwQAAAAAeHg=') [22001-232]
2024-11-05 16:45:35.183279+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:45:36.081134+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:45:36.460266+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:45:36.748394+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 16:49:23.897188+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.findHolder(HoldersDBH2.java:37)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:18)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-11-05 16:49:23.948156+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.HoldersDBH2.addHolder(HoldersDBH2.java:22)
	at controllers.MainController.create(MainController.java:18)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2024-11-05 17:05:34.014509+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE ACCOUNTSDB ( \000d\000a accountNumber VARCHAR(20) NOT NULL,\000d\000a accounts VARCHAR(1000) NOT NULL, \000d\000a[*])"; ожидалось "identifier"
Syntax error in SQL statement "CREATE TABLE ACCOUNTSDB ( \000d\000a accountNumber VARCHAR(20) NOT NULL,\000d\000a accounts VARCHAR(1000) NOT NULL, \000d\000a[*])"; expected "identifier"; SQL statement:
CREATE TABLE ACCOUNTSDB ( 
 accountNumber VARCHAR(20) NOT NULL,
 accounts VARCHAR(1000) NOT NULL, 
) [42001-232]
2024-11-05 18:20:00.916264+03:00 jdbc[6]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 13 more
2024-11-05 18:20:00.924258+03:00 jdbc[6]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 13 more
2024-11-05 18:20:39.059866+03:00 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "ID" не найден
Column "ID" not found; SQL statement:
DELETE FROM HOLDERSDB WHERE ID=1 [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Delete.doPrepare(Delete.java:110)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-05 18:24:14.915641+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:24:15.316956+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:24:15.422998+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:24:15.577056+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:32:40.240854+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "NAME" не найден
Column "NAME" not found; SQL statement:
DELETE FROM ACCOUNTSDB WHERE name='Иванов' [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Delete.doPrepare(Delete.java:110)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-05 18:32:44.499086+03:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "NAME" не найден
Column "NAME" not found; SQL statement:
DELETE FROM ACCOUNTSDB WHERE name='Иванов' [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Delete.doPrepare(Delete.java:110)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-05 18:39:19.445661+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:39:19.857918+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:39:20.234995+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:39:20.435989+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-05 18:40:23.634295+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "ACCOUNTERSDB" не найдена
Table "ACCOUNTERSDB" not found; SQL statement:
select * from ACCOUNTERSDB [42102-232]
2024-11-08 13:06:50.418484+03:00 jdbc[5]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 13 more
2024-11-08 13:57:02.784651+03:00 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "DELETE FROM ACCOUNTSDB WHERE[*]"; ожидалось "INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "DELETE FROM ACCOUNTSDB WHERE[*]"; expected "INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
DELETE FROM ACCOUNTSDB WHERE [42001-232]
2024-11-08 13:57:28.987290+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 13:57:31.098729+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 13:57:33.017150+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 13:57:34.315628+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 13:59:14.141053+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.AccountsDB.findAccount(AccountsDB.java:42)
	at models.BankAccount.accountNumberGeneration(BankAccount.java:35)
	at models.BankAccount.<init>(BankAccount.java:11)
	at models.AccountHolder.<init>(AccountHolder.java:20)
	at controllers.MainController.create(MainController.java:17)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 17 more
2024-11-08 14:07:34.731877+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:07:35.119648+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:07:35.479273+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:07:35.644666+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:28:02.132413+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.AccountsDB.findAccount(AccountsDB.java:42)
	at models.BankAccount.accountNumberGeneration(BankAccount.java:36)
	at models.BankAccount.<init>(BankAccount.java:11)
	at models.AccountHolder.<init>(AccountHolder.java:20)
	at controllers.MainController.create(MainController.java:17)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 17 more
2024-11-08 14:31:01.527785+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:31:01.910343+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:31:02.285067+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:31:02.468072+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:34:07.939720+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:34:08.317187+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:34:08.663157+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:34:08.846731+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:37:31.768904+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:37:32.134695+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:37:32.487028+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:37:32.656188+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:38:43.474044+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:41:13.136130+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "FROMHISTORYOPERATIONS" не найдена
Table "FROMHISTORYOPERATIONS" not found; SQL statement:
DELETE fromHISTORYOPERATIONS [42102-232]
2024-11-08 14:41:37.984394+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:41:38.350434+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:41:38.725590+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:41:38.896714+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:42:38.718275+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:47:39.280508+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.AccountsDB.findAccount(AccountsDB.java:42)
	at models.BankAccount.accountNumberGeneration(BankAccount.java:36)
	at models.BankAccount.<init>(BankAccount.java:11)
	at models.AccountHolder.<init>(AccountHolder.java:20)
	at controllers.MainController.create(MainController.java:17)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 17 more
2024-11-08 14:48:28.515004+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:50:48.247990+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:53:45.513520+03:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at models.AccountsDB.findAccount(AccountsDB.java:42)
	at models.BankAccount.accountNumberGeneration(BankAccount.java:36)
	at models.BankAccount.<init>(BankAccount.java:11)
	at models.AccountHolder.<init>(AccountHolder.java:20)
	at controllers.MainController.create(MainController.java:17)
	at Main.main(Main.java:7)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/stadm-DenisP/Desktop/Task9BANK/BD.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 17 more
2024-11-08 14:54:00.729095+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:54:01.282287+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:54:01.636614+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:54:01.785498+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:54:19.178942+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:58:29.258784+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 14:59:04.171659+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:12:20.756477+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:12:21.326302+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:12:21.667692+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:12:21.824061+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:38:02.763707+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNTSDB VALUES ('07835280944247185082', 0, 'Иванов Иван Иванович',[*]);"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO ACCOUNTSDB VALUES ('07835280944247185082', 0, 'Иванов Иван Иванович',[*]);"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO ACCOUNTSDB VALUES ('07835280944247185082', 0, 'Иванов Иван Иванович',); [42001-232]
2024-11-08 15:38:28.443104+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNTSDB VALUES ('90472100905299466131', '0', 'Иванов Иван Иванович',[*]);"; ожидалось "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "INSERT INTO ACCOUNTSDB VALUES ('90472100905299466131', '0', 'Иванов Иван Иванович',[*]);"; expected "DEFAULT, INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO ACCOUNTSDB VALUES ('90472100905299466131', '0', 'Иванов Иван Иванович',); [42001-232]
2024-11-08 15:38:54.626951+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:38:55.181355+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:38:55.343606+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:38:55.503700+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:59:30.374293+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:59:30.933200+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:59:31.121164+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 15:59:31.286098+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-08 16:00:30.318302+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "select * from ACCOUNTSDB\000d\000a[*]select * from HISTORYOPERAT"
Syntax error in SQL statement "select * from ACCOUNTSDB\000d\000a[*]select * from HISTORYOPERAT"; SQL statement:
select * from ACCOUNTSDB
select * from HISTORYOPERAT [42000-232]
2024-11-08 16:00:42.435847+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "select * from ACCOUNTSDB,\000d\000a[*]select * from HISTORYOPERAT"; ожидалось "identifier"
Syntax error in SQL statement "select * from ACCOUNTSDB,\000d\000a[*]select * from HISTORYOPERAT"; expected "identifier"; SQL statement:
select * from ACCOUNTSDB,
select * from HISTORYOPERAT [42001-232]
2024-11-08 16:00:45.577064+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "HISTORYOPERAT" не найдена
Table "HISTORYOPERAT" not found; SQL statement:
select * from HISTORYOPERAT [42102-232]
2024-11-08 16:01:03.433813+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "HISTORYOPERATION" не найдена
Table "HISTORYOPERATION" not found; SQL statement:
select * from HISTORYOPERATION [42102-232]
2024-11-13 18:55:31.234915+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "select * from HOLDERSDB\000d\000a[*]select * from ACCOUNTSDB\000d\000aselect * from HISTORYOPERATIONS"
Syntax error in SQL statement "select * from HOLDERSDB\000d\000a[*]select * from ACCOUNTSDB\000d\000aselect * from HISTORYOPERATIONS"; SQL statement:
select * from HOLDERSDB
select * from ACCOUNTSDB
select * from HISTORYOPERATIONS [42000-232]
2024-11-13 18:55:58.543105+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "select * from HOLDERSDB,\000d\000a[*]select * from ACCOUNTSDB,\000d\000aselect * from HISTORYOPERATIONS"; ожидалось "identifier"
Syntax error in SQL statement "select * from HOLDERSDB,\000d\000a[*]select * from ACCOUNTSDB,\000d\000aselect * from HISTORYOPERATIONS"; expected "identifier"; SQL statement:
select * from HOLDERSDB,
select * from ACCOUNTSDB,
select * from HISTORYOPERATIONS [42001-232]
2024-11-13 19:01:40.987158+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:01:46.709106+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:01:52.149627+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:01:57.779585+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:21:56.994746+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:21:57.491382+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:21:57.679245+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
2024-11-13 19:21:57.883095+03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Нет данных
No data is available [2000-232]
